---
- districtName: "shopping"
  landItems:
   - "Empty Can"
   - "Stick"
  waterItems:
   - "River Reed"
   - "Stick"
- districtName: "business"
  landItems:
   - "Empty Can"
   - "Stick"
  waterItems:
   - "River Reed"
   - "Empty Can"
- districtName: "residential"
  landItems:
   - "Empty Can"
   - "Stick"
  waterItems:
   - "River Reed"
