---
- districtName: "shopping"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Bandage"
   - "Radio Antenna"
   - "Medicine Box"
   - "Scrap Metal"
  waterItems:
   - "River Reed"
   - "Stick"
   - "Umbrella"
- districtName: "business"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Rope"
   - "Notebook"
   - "Paper Scrap"
   - "Scrap Metal"
   - "Golf Club"
   - "Rope"
  waterItems:
   - "River Reed"
   - "Empty Can"
- districtName: "residential"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Match"
   - "Matchbook"
   - "Bandage"
   - "Egg"
   - "Pipe"
  waterItems:
   - "River Reed"
   - "Umbrella"
   - "Rope"
