---
- districtName: "shopping"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Bandage"
   - "Radio Antenna"
   - "Medicine Box"
   - "Scrap Metal"
   - "Holy Basil"
   - "Water Chestnut"
   - "Log"
   - "Egg"
   - "Match"
   - "Matchbook"
   - "Plastic Bottle"
   - "Wood Plank"
   - "Pipe"
  waterItems:
   - "River Reed"
   - "Stick"
   - "Umbrella"
   - "Water Chestnut"
   - "Lotus Root"
   - "Log"
   - "Water Cress"
   - "Plastic Bottle"
   - "Wood Plank"
   - "Seaweed"
- districtName: "business"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Rope"
   - "Notebook"
   - "Match"
   - "Matchbook"
   - "Paper Scrap"
   - "Scrap Metal"
   - "Golf Club"
   - "Rope"
   - "Radio Antenna"
   - "Plastic Bottle"
   - "Metal Hook"
  waterItems:
   - "River Reed"
   - "Empty Can"
   - "Lotus Root"
   - "Rope"
   - "Stick"
   - "Log"
   - "Hardwood Log"
   - "Water Cress"
   - "Plastic Bottle"
   - "Seaweed"
- districtName: "residential"
  landItems:
   - "Empty Can"
   - "Stick"
   - "Match"
   - "Matchbook"
   - "Bandage"
   - "Egg"
   - "Pipe"
   - "Coneflower"
   - "Water Chestnut"
   - "Medicine Box"
   - "Plastic Bottle"
   - "Metal Hook"
   - "Wood Plank"
  waterItems:
   - "River Reed"
   - "Umbrella"
   - "Rope"
   - "Water Chestnut"
   - "Lotus Root"
   - "Water Cress"
   - "Plastic Bottle"
   - "Wood Plank"
   - "Seaweed"
