---
- districtName: "shopping"
  items:
   - "River Reed"
   - "Empty Can"
   - "Stick"
- districtName: "business"
  items:
   - "River Reed"
   - "Empty Can"
   - "Stick"
- districtName: "residential"
  items:
   - "River Reed"
   - "Empty Can"
   - "Stick"



